### ISSUE TITLE
FS24 update 1.2.7.0 broken AutoFPS?

### ISSUE THREAD

**Issue by Pogman** [kayjay1c6b/MSFS2024_AutoFPS-by-kayJay_1c6#6]
Looks like the recent update may have stopped AutoFPS from finding the TLOD / OLOD vars.

I set the TLOD to 55 and OLOD to 195 and sat on the runway and restarted AutoFPS several times but it doesn't seem to find the vars to adjust. It was working previous to the FS update.

Just a heads up. Thanks for your effort on this.

**Comment by edueocara27** [comment]
The original author of autoFPS is already testing a version compatible with MSFS 2024 and has already updated it to work with the latest MSFS 2024 update.

https://github.com/ResetXPDR/MSFS2020_AutoFPS/releases/tag/v0.4.3.2-test

I don't know if the author of this version will continue to update it, since the original author now has an updated version that already works better than this one. I don't think it would make sense to create competition, since this version is basically an old version of autoFPS with a workaround to make it work on 2024.

**Comment by ResetXPDR** [comment]
> I don't know if the author of this version will continue to update it, since the original author now has an updated version that already works better than this one. I don't think it would make sense to create competition, since this version is basically an old version of autoFPS with a workaround to make it work on 2024.

I am the original AutoFPS author and all my version does is add 2024 support to the existing functionality that my 0.4.3.1 version provided. I believe this author based his app on that same 0.4.3.1, made it 2024 specific and has added new features, the latter of which I do not intend to do hence there is no competition as such. 

In short if you want what you had in 2020, and no more, but also in 2024 then mine is the one to use. If you want new capabilities in 2024 then this is the one to use. 

Compatibility with the latest 2024 version should come soon to this app as we have been working together on compatibility. I have already passed on to him what small change I did to get it working with this 2024 update.

I'm sure this author will get compatibility

**Comment by kayjay1c6b** [comment]
I have updated the app to version 1.0.2.0. This version adapts to the newest update of MSFS 2024.

Improvements:

-  There is no longer need to set predefined TLOD and OLOD
- The issue with going to the menu / walkaround resseting the app's connection to the sim is resolved
- The issue with dissapearing window should be resolved

New functionalities:

- The app now detects (in vr optimized mode) category of your aircraft based on weight and adds some TLOD to smaller planes (you usually have better performance with them) and takes away some TLOD for heavier planes. So set your TLOD min and max somewhere in the middle and you will see how TLOD min and max change based on aircraft size next to ATLOD. Have a play with it and let me know what do you think.

**Comment by siglr** [comment]
There shouldn't be two versions of the same app. Please join efforts and make only one!
@ResetXPDR 
@kayjay1c6b

**Comment by Pogman** [comment]
@kayjay1c6b seems to working ok now with this version cheers.
